### ISSUE TITLE
Access blocked: Tidyverse API Packages’s request is invalid

### ISSUE THREAD

**Issue by edgar-manukyan** [r-lib/gargle#265] opened 2023-06-16 18:52 UTC
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Dear developers,

I used gargle 1.5.0 and it seems that the API is blocked

```r
gargle::token_fetch()
```

```
Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)
```

![image](https://github.com/r-lib/gargle/assets/125491785/e7bad974-c796-4d33-addb-bd4241f20c00)

```
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.1                         
year           2021                        
month          08                          
day            10                          
svn rev        80725                       
language       R                           
version.string R version 4.1.1 (2021-08-10)
nickname       Kick Things 
```

![image](https://github.com/r-lib/gargle/assets/125491785/7d29d6ed-520c-4adf-a157-6b03a2dc5e06)

**Comment by edgar-manukyan** [comment] 2023-06-16 19:05
Interestingly downgrading to 1.4.0 helps:
```
devtools::install_version('gargle', '1.4.0')
```

**Comment by jennybc** [comment] 2023-06-16 20:40
Duplicate of https://github.com/r-lib/gargle/issues/263 and https://github.com/tidyverse/googledrive/issues/433. I've fixed this in the development version of gargle but I can't release it until it's at least 1 week after the previous release. So the fix will be in a patch release on CRAN soon.

**Closed by jennybc** 2023-06-16 20:40 UTC

**Comment by ries9112** [comment] 2025-03-13 05:36
Sorry to bother on this thread, but experiencing this today:

<img width="1115" alt="Image" src="https://github.com/user-attachments/assets/90d68837-9248-4fcb-a142-667af24cbd84" />

I tried `devtools::install_version('gargle', '1.4.0')` and `pak::pak("r-lib/gargle")` but seeing the same thing

```r
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.3                         
year           2024                        
month          02                          
day            29                          
svn rev        86002                       
language       R                           
version.string R version 4.3.3 (2024-02-29)
nickname       Angel Food Cake     
```

**Comment by jennybc** [comment] 2025-03-13 18:41
I've been using gargle-using package a bit recently, including from desktop and a server, with success, so there's not some generalized problem at the moment. There has to be more to the story. I'd encourage you to open a new issue with details for others to reproduce.
