### ISSUE TITLE
[Action Required] Migrate your impacted OAuth out-of-band clients to an alternative method before October 3, 2022

### ISSUE THREAD

**Issue by selesnow** [r-lib/gargle#208] opened 2022-08-25 07:16 UTC
Hello Jenny

I am use gargle inside `rgoogleads` package inside [auth function block](https://github.com/selesnow/rgoogleads/blob/master/R/gads_auth.R).

[Out-Of-Band (OOB) flow Migration Guide](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)

I have verified oauth client for this package:
![](http://img.netpeak.ua/alsey/1CIIV1K.png)

And i recived notifycation from Google Developers team "[Action Required] Migrate your impacted OAuth out-of-band clients to an alternative method before October 3, 2022"

-------------------------
Hello Google OAuth Developer,

We're writing to remind you that the OAuth out-of-band (OOB) flow will be deprecated on October 3, 2022, to protect your users from phishing and app impersonation attacks.

Please check our recent blog post about [Making Google OAuth interactions safer](https://notifications.google.com/g/p/APNL1TijWmNg6sYYioUg9vcChvAjprYzdRGu99ifYPWRc4wz3o4-u1tnaxQ62ukjHt4sQW8drkb7js9Xp-QKapLVO-yHnTFCJuL9dCNyIGCfvSEMJBismrjSyVCW9qD6THFtcl_GkrSl-C_vJGom) for more information.

What do I need to do?
No action is required on your part as apps using OOB in [testing](https://notifications.google.com/g/p/APNL1TixNRSzRhR_0mxb_ajat2Z88g50HZ6Y7nBeAC5IE1M6uMt0Q_7kiT0voXiY3oCa-3S0x6PVjR7fznmR6kO1jprSrUjqpVJxGb8yBfRzm1am47uN2BHO16R0UrK2Ycctif2wDEWn0fAFl9WpJZUSf_Nw000NEiwC) mode will not be affected by this change. However, we strongly recommend migrating to safer methods as these apps will be immediately blocked when switching to [in production](https://notifications.google.com/g/p/APNL1TjuniDry9b3SHNHIxpgeDXrLmD16gzAsj8RwYDWdfULZA9gEYucitv4oZeONsbafRzfPtwq7JkQuF3M1tEMSQc2HyzNWHIH9UPfYp9XSjdQ83T1sIq9IguM7HsNoho2cCy-Vs7siBGtdP_eLXmlOIPkp8l_pRu6ptGN) status.

If you want to publish your app(s) to production, follow these instructions:

Determine your app(s) [client type](https://notifications.google.com/g/p/APNL1TiVpKC9sKINHy5WDVstOqd1tt92FDSnP2NQkHbrK3RqZLWc5sR8I5inmuZ1Uofi-qrre_qC0sQlKzoKwctn4KjD6PwBRxqE8q7HmW-z2D_3DCBTdzXSqqxlyDCKajUuziCg9-ZfnyM7_LoTbc0ivfu5pH14tpM84m0dW3NglDhqMnVf) from your Google Cloud project by following the client links below.
Follow the [migration guide](https://notifications.google.com/g/p/APNL1TgV6Huq7Ib1SWQkBIWYyR_5m-vO3MKu9EDyPfFIopwkCE-kWkk4HKKNZweaWZu0DB2Xnjbdc7E68zUGJFZUrMajPewhfNnTx7TD3GHHZQhGmrOqmbw2VGK5XCzhP3FeKXqfBDfisKbAUiq7ZEJyDWGwbqc) to migrate your app(s) to an alternative method

**Comment by selesnow** [comment] 2022-08-25 08:44
Do i need make any action?

**Comment by jennybc** [comment] 2022-08-30 15:09
Yes, it really is true that OOB auth is going away. New clients have not been able to enable OOB for a while now. Existing clients will, in general, stop having access to the OOB flow on October 3. This impacts gargle (and several downstream packages) as well, which is being tracked in #202. However, I believe our client will continue to have OOB auth for a bit longer, due to an extension.

Two things I don't know about your app:

* Is it in testing mode? Vs. production. The text you give above suggests that is true. Maybe because it's only used by your or colleagues? In that case, maybe OOB auth will continue to work. I don't know.
* Do you really need OOB? I.e. do you use your package interactively from RStudio Workbench or similar? If not, then the loss of OOB auth might not affect your actual workflow.

**Comment by jennybc** [comment] 2022-09-07 18:58
I'm going to call this a duplicate of #202 

Before the end of September, I'll be doing a release of gargle (in addition to a hot fix I'm about to do today) that makes a few things around using OOB or avoiding OOB easier. But mostly all I can do in gargle itself is to better document things. That will probably also come with a blog post.

**Closed by jennybc** 2022-09-07 18:58 UTC
