### ISSUE TITLE
Ability to pass token breaks in 1.2.1?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/gargle#217] opened 2022-10-12 04:49 UTC
I had a report in https://github.com/cloudyr/googleCloudStorageR/issues/167 that creating a user token manually and passing it in to authenticate has stopped working. Is there anything that comes to mind that may have caused it?

**Comment by jennybc** [comment] 2022-10-13 17:56
That report is a bit muddled, as OP seems to be confusing scopes (which look like URLs) with the URLs that NEWS bullet is referring to (actual URLs used in the token exchange process).

But to answer the question, no, there is no intentional change that would seem to explain this. I think you'll need to get more detail.

**Comment by jennybc** [comment] 2022-10-21 18:32
I'm going to close this as I currently don't have any specific action to take. But obviously please come back if you start to evidence of some sort of regression.

**Closed by jennybc** 2022-10-21 18:32 UTC

**Comment by MarkEdmondson1234** [comment] 2022-10-21 20:08
Yep I'll ask for more details and they can elaborate perhaps. Been following the recent updates and looking great :) many thanks

**Comment by jennybc** [comment] 2022-10-21 22:15
Likewise, thanks for googleComputeEngineR! That was extremely useful in my recent GCE forays, where I am very unfamiliar with the landscape.
