### ISSUE TITLE
googlesheets4 - Resource Exhausted erro

### ISSUE THREAD

**Issue by tstratopoulos** [r-lib/gargle#160] opened 2020-12-03 18:09 UTC
I was using read_sheet() and I received the following error: 

Client error: (429) RESOURCE_EXHAUSTED
  * Either out of resource quota or reaching rate limiting. The client should look for google.rpc.QuotaFailure error detail for more information.
  * Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'sheets.googleapis.com' for consumer 'project_number:603366585132'.

Error details:
  * Error details of type 'google.rpc.ErrorInfo' are not implemented yet.
  * Workaround: use `tryCatch()` and inspect error payload yourself.
  * Please open an issue at https://github.com/r-lib/gargle/issues, so we can fix.

**Comment by jennybc** [comment] 2020-12-03 19:33
Duplicate of #146 and #159

**Closed by jennybc** 2020-12-03 19:33 UTC
